import Nav from "@/components/Nav";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";

export const metadata = {
  title: "To Do",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>

      <body>
        <Nav />
        {children}
      </body>
      </AuthProvider>
    </html>
  );
}
